### ISSUE TITLE
escape doesn't close native "find in project"

### ISSUE THREAD

**Issue by leshek-pawlak** [itlamb/case-keep-replace#1]
Atom version: 1.12.2

escape doesn't close "find in project" bar.

**Comment by itlamb** [comment]
Thanks for feedback :) I'll check this

**Comment by itlamb** [comment]
Hey @leshek-pawlak, please check new version :)

**Comment by leshek-pawlak** [comment]
Works great! Thanks! You rock! 💯  👍
