### ISSUE TITLE
Replace underscore separated const like strings

### ISSUE THREAD

**Issue by thmsobrmlr** [itlamb/case-keep-replace#2]
It would be great if this package could also replace underscore separated const like strings. This could be an additional replace or a separate option.

For example when replacing `MyTest` with `NewName`, it should also replace `MY_TEST` with `NEW_NAME`. Currently it only handles consts like `MYTEST`, without underscore.

Let me know what you think.

**Comment by itlamb** [comment]
Good idea @thomas88. I think that it could affect only words written in capitals only, so for example `mySQL` should stay untouched.

**Comment by itlamb** [comment]
@thomas88 Please check new 0.6.0 version and let me know if it works as you expected.

**Comment by thmsobrmlr** [comment]
Awesome! Exactly what I needed and incredible turnaround speed. Thanks @itlamb
