### ISSUE TITLE
Selector does not focus the case-keep-replace pop-up dialog when opening the dialog

### ISSUE THREAD

**Issue by opqpop** [itlamb/case-keep-replace#3]
Repro:

1. ctrl-cmd-r to open case-keep-replace:toggle
2. now I have to move my mouse to select the typeahead for "Find ... (camelCase)"

Is there any way it can just directly focus the typeahead after toggling case-keep-replace, so that I don't have to use my mouse? Ex: if I want to find replace "abc" to "def", I want to be able to do it via the sequence: ctrl-cmd-r, abc, tab, def, enter

**Comment by NullVoxPopuli** [comment]
I have this issue too

**Comment by itlamb** [comment]
Hello @opqpop, @NullVoxPopuli, thanks for your feedback! Please check the released patch 0.6.1 with a fix of this issue.
