### ISSUE TITLE
Integrate with CMD+D behavior?

### ISSUE THREAD

**Issue by ProLoser** [itlamb/case-keep-replace#4]
On VSCode they have a similar plugin but it hooks into the existing CMD+D behavior which lets you grab multiple strings on the page and edit or replace all of them in parallel. Do you think you could recreate such behavior (maybe make it an option we can enable).

https://marketplace.visualstudio.com/items?itemName=Cardinal90.multi-cursor-case-preserve

![VSCode Extension](https://github.com/Cardinal90/multi-cursor-case-preserve/raw/master/images/Example.gif)

**Comment by itlamb** [comment]
Hey, thanks for your feedback! I think it is much different behavior than it is now - I'd rather stay with a popup as it doesn't mess the code during typing (subjective opinion of course)

**Comment by ProLoser** [comment]
This allows you to preview what it will look like to confirm it's correct though
